<?php

return array (
    'Covid-19 solidarity' => 'Covid-19 solidarity',
    'Would you like to give your neighbour a helping hand?' => 'Envie de donner un coup de main &agrave; votre voisin ?',
    'Join the movement and propose to help your neighbour by grocery shopping for them to provide for their basic needs.' => 'Rejoignez notre mouvement et proposez &agrave; votre voisin de faire ses courses de premi&egrave;re n&eacute;cessit&eacute;.',
    'Share' => 'Partager',
    'Join us in the movement and propose to help your neighbours by grocery shopping for their basic needs' => 'Rejoignez notre mouvement et proposez à votre voisin de faire ses courses de première nécessité.',
    'I want to help' => 'Je veux aider',
    'Need help? Click here' => 'Besoin d’aide? Cliquez ici',
    'Let’s spread solidarity, not the virus' => 'Répandons la solidarité, pas le virus',
    'In order to slow down the circulation of the virus, the government and the medical staff strongly recommend the population to stay home isolated. How can we access basic needs and feed ourselves if we’re stuck at home in isolation?' => 'Pour endiguer rapidement la propagation du virus, le gouvernement et le milieu médical recommandent fortement à la population de rester à domicile. Mais comment faire pour s’alimenter et se fournir en produits de première nécessité tout en restant chez soi ?',
    'How does it work?' => 'Comment ça marche ?',
    '“I would like to get help”' => '“Je souhaite obtenir de l’aide”',
    'Print out your shopping list and ask your neighbour to do the shopping for you.' => 'Imprimer la liste de course ou demandez à votre voisin de le faire pour vous.',
    'Stick it to your door or put it in the hallway.' => 'Postez-la sur votre fenêtre, collez-la à votre porte ou placez-la dans votre halld’entrée.',
    'Wait for a helping neighbour to fetch the list. (S)He will contact you and deliver to you as soon as possible.' => 'Attendez qu’un voisin la récupère. Il prendra contact avec vous et vous livrera sans tarder.',
    'Print out your shopping list' => 'Imprimer la liste de course',
    'Find someone to help me' => 'Trouver quelqu\'un pour m\'aider',
    '“I can help ”' => '“Je suis un bénévole et je veux aider”',
    '<a class="text-underline" href="https://docs.google.com/forms/d/e/1FAIpQLSftvX-pPQZePG8K46Npk8pBvUUP5Da7MP8CXPbtL-wAz0spcw/viewform" target="_blank"><u><b>Fill out this form</b></u></a> 📝' => '<a class="text-underline" href="https://docs.google.com/forms/d/e/1FAIpQLSftvX-pPQZePG8K46Npk8pBvUUP5Da7MP8CXPbtL-wAz0spcw/viewform" target="_blank"><u><b>Compléter le formulaire</b></u></a> 📝',
    '<a class="text-underline" href="./files/EN.pdf" target="_blank"><u><b>Print out the template</b></u></a> “shopping list” in A4 format 🖨️' => '<a class="text-underline" href="./files/FR.pdf" target="_blank"><u><b>Imprimer le modèle</b></u></a> “liste de course” en format A4 🖨️',
    'Share it or place it in your neighbour’s mailbox 📬' => 'Partagez-la ou placez-la dans la boite aux lettre de votre voisin 📬',
    'Go back home and enjoy a coffee ☕' => 'Retournez chez vous et discutez avec vos proches autour d’un café. ☕',
    'Take your neighbour’s filled in shopping list and tell him/her you’ll go shop for him 🚶' => 'Prenez une photo de la liste de courses et prévenez pat téléphone votre voisin ! 📝',
    'Go to the store, try not to empty the shelves if you have what you need, be mindful to others. 📝' => 'Rendez-vous en magasin et ne dévalisez pas les étagères. 🎒',
    'Preferably use a shopping cart instead of a shopping basket, you create additional distance. 🛒' => 'Utilisez de préférence un caddie à la place d’un panier, vous créez ainsi une distance supplémentaire. 🛒',
    'Come alone. 🚶‍♂️' => 'Venez de préférence seul. 🚶‍♂️️',
    'Only touch products you are gonna buy. 🤚' => 'Touchez uniquement les produits que vous achetez. 🤚',
    'Pay electronically. 💳' => 'ayez de manière électronique. 💳',
    'Go back to your neighbour’s home, put the groceries down in front of the door, and ring! 🎒' => 'Retournez délivrer les produits devant la porte et sonnez à la porte ! 🚪',
    '<b>Mission accomplished, thank you very much for your help!</b> 🚀 💚' => '<b>Mission réussie, merci infiniment pour votre collaboration !</b> 🚀 💚',
    'Now you can also share a picture on Facebook or Instagram with #covidsolidarity 📸' => 'Partagez une photo sur Facebook avec le #covidsolidarity 📸',
    'Rules to respect' => 'Mesures à respecter',
    'Wear gloves when you go shopping (when you take the groceries and put them in the bags). Touch only the products you buy.' => 'Mettez des gants lorsque vous faites les courses (quand vous prenez les produits et les mettez dans les sacs de courses). Touchez uniquement les produits que vous achetez.',
    'Use a shopping cart instead of a shopping bag, you create thus additional distance.' => 'Utilisez un caddie à la place d\'un panier, vous créez ainsi une distance supplémentaire.',
    'Preferably come alone.' => 'Venez de préférence seul.',
    'Keep a distance of 3 meters between the receiver and the volunteer. By all means, avoid physical contact, practice social distancing with vulnerable people. Avoid social contact as much as possible.' => 'Gardez une distance de 3 mètres entre la personne isolée et le bénévole et évitez tout contact physique avec les personnes fragiles. Évitez aussi tout contact avec d’autres personnes.',
    'Wash your hands regularly or use a hand disinfectant after the delivery (this is for both the receiver and the volunteer of the delivery)' => 'Lavez-vous les mains régulièrement ou utilisez une solution hydro-alcoolique après la livraison, surtout après avoir réceptionné la marchandise, touché la liste de courses ou tout autre papier.',
    'Avoid touching door handles and other metallic objects during the delivery. When contacting between the receiver and the volunteer, communicate by phone or through a message application (WhatsApp or Messenger for example).' => 'Évitez de toucher les poignées de porte et autres objets métalliques lors de la livraison. Privilégiez les appels ou messages/whatsapp.',
    'Pay electronically.' => 'Payez de manière électronique.',
    'Cover your mouth and nose with a tissue when you cough or sneeze or use the inside of your elbow.' => 'Si vous n’avez pas de mouchoir à portée de main, éternuez ou toussez dans le pli du coude.',
    'Be careful with vulnerable groups i.e. Senior-aged individuals +65, diabetics, people suffering from heart diseases, pulmonary insufficiency, renal failure, and immunosuppressed patients and many others.' => 'Faites attention aux groupes à risque (personnes de plus de 65 ans, diabétiques, personnes souffrant de maladies cardiaques, pulmonaires ou rénales, personnes immunodéprimées, ...).',
    'If a volunteer is not delivering we recommend you stay home safe and avoid social contact.' => 'Le reste du temps (quand vous n’effectuez pas de livraisons), nous vous invitons à rester chez vous et à limiter au maximum vos contacts avec d’autres personnes.',
    'For more information visit our page: <a href="https://www.info-coronavirus.be/" target="_blank">https://www.info-coronavirus.be/</a>' => 'Plus de détails sur : <a href="https://www.info-coronavirus.be/fr/" target="_blank">https://www.info-coronavirus.be/fr/</a>',
    'Do you have any questions ? We’ve got the answers !' => 'Vous avez des questions ? Nous avons les réponses !',
    '“I would like to help”' => '“Je suis un bénévole et je veux aider”',
    'Will I get paid to help my neighbour?' => 'Suis-je rémunéré pour venir en aide à mon voisin ?',
    'No, we are acting strictly on a voluntary basis. But of course your neighbour is free to decide how (s)he would like to thank you.' => 'Non, nous agissons dans une approche strictement citoyenne et bénévole. Mais libre à votre voisin de vous remercier à sa guise s’il le souhaite.',
    'I don’t want to pay the money upfront' => 'Je ne souhaite pas avancer de l’argent',
    'This is a condition you need to fill in order to help your neighbour. Not to make it too expensive, we advise you to only provide for basic needs.' => 'C’est une condition indispensable pour aider un voisin. Pour alléger votre portefeuille, nous vous invitons à n’acheter que des biens de première nécessité.',
    'How to hand over groceries to someone inside a building?' => 'Comment déposer les courses au sein d’un immeuble ?',
    'You just have to make contact with the person you want to do the shopping for, and tell him at what time you will put the groceries in front of his door. Don’t forget rules for proper hygiene.' => 'Il suffit de prendre contact avec votre voisin pour lui indiquer l’heure à laquelle vous déposerez les courses devant sa porte. N’oubliez pas de respecter les règles d’hygiène.',
    'How will I get refunded?' => 'Comment vais-je être remboursé ?',
    'It’s very simple ! The only thing you have to do is to write down your bank account number on the shopping list that you will give back to your neighbour. Your neighbour will pay you back as soon as possible.' => 'C’est très simple ! Il suffit d’indiquer votre numéro de compte sur la liste de course que vous rendrez à votre voisin. Pour le bon service rendu, il vous remboursera sans tarder.',
    'Can I contact the person who helped me again in the future?' => 'Est ce que je peux recontacter l’aide-bénévole par la suite ?',
    'Of course ! The goal is that the two of you can meet in order to create a relationship of trust. Nevertheless, do not forget the rules of hygiene in order to stay safe.' => 'Bien sûr! Le but de cette initiative est que vous vous rencontriez afin de créer une relation de confiance. Vous pouvez donc rappeler l’aide-bénévole quand bon vous semble. Cependant, n’oubliez pas les consignes d’hygiène strictes pour toujours rester en sécurité.',
    'How to know who is shopping for me?' => 'Comment savoir qui s’occupe de faire mes courses ?',
    'When your helper takes your shopping list, he will contact you on your phone number to inform you that (s)he is on her/his way.' => 'Lors de la récupération de la liste de course, l’aide-bénévole vous contactera sur votre numéro de téléphone fixe ou mobile pour vous informer qu’il est en route vers le magasin. Il vous indiquera aussi quand il est sur le chemin du retour.',
    'I am not able to easily send money' => 'Je n’ai pas la possibilité de faire un versement facilement',
    'You can ask a friend or a family member to help you pay back the person who did the shopping for you or download a payment application on your mobile phone. The best is to ask for help.' => 'Vous pouvez demander à un proche de vous aider pour rembourser le bénévole ou télécharger les applications de paiement depuis votre téléphone portable.',
    'What is the maximum amount that I can order for?' => 'Quel est le montant maximal que je peux commander ?',
    'You can order for as much as you’d like, but we advise not to go over 25 to 30 euros and focus on your basic needs. Also mind the weight of the shopping bag, the person who will deliver it to you will have to carry it.' => 'Comme bon vous semble, mais nous suggérons de ne pas dépasser un montant de 25 à 30€ et de se focaliser sur des biens de première nécessité. Pensez aussi au poids final de votre colis, l’aide bénévole doit pouvoir se déplacer à pied avec.',
    'With the help of' => 'Avec le soutien de',
    'A 100% voluntary initiative' => 'Une initiative 100% bénévole et citoyenne',
    'We were touched by the way the Covid-19 crisis turned out to affect our community. This epidemic forced us to find pragmatic solutions to bring help to those in need. We decided to serve the population through collective intelligence.' => 'Marqué par la tournure des événements et conscients que cette crise nous force à trouver des solutions d’aide pragmatiques, nous avons souhaité par la voie de l’intelligence collective rendre service à la population.',
    'A non-profit citizen movement created online by a group of entrepreneurs and students from the BeTech Community who wanted to create a positive social impact .' => 'Un mouvement citoyen et non-lucratif initié en ligne par un groupe d’entrepreneurs et étudiants de la communauté BeTech qui permet de créer du lien social dans une démarche bienveillante.',
    '❤️ Made with love to beat Covid-19' => '❤️ Made with love to beat Covid-19',
    'Contact' => 'Contact',
    'Join the movement on Facebook' => 'Join the movement on Facebook',
);
