<?php

return array (
    'Covid-19 solidarity' => 'Covid-19 solidarity',
    'Would you like to give your neighbour a helping hand?' => 'Zin om je buren een handje te helpen?',
    'Join the movement and propose to help your neighbour by grocery shopping for them to provide for their basic needs.' => 'Wil je je buurman helpen? Sluit je aan bij de beweging die voor je buurman/-vrouw zijn/haar boodschappen voor meest noodzakelijke levensbehoeften kan doen.',
    'Share' => 'Delen',
    'Join us in the movement and propose to help your neighbours by grocery shopping for their basic needs' => 'Sluit je aan bij onze beweging en stel aan je buren voor om voor hen de meest belangrijke boodschappen te doen.',
    'I want to help' => 'Ik wil helpen',
    'Need help? Click here' => 'Hulp nodig? Klik hier',
    'Let’s spread solidarity, not the virus' => 'Laten we de solidariteit verspreiden, niet het virus...',
    'In order to slow down the circulation of the virus, the government and the medical staff strongly recommend the population to stay home isolated. How can we access basic needs and feed ourselves if we’re stuck at home in isolation?' => 'Om de verspreiding van het virus snel in te dammen, raden de overheid en de medische experts sterk aan om zoveel mogelijk thuis te blijven. Maar hoe kunnen mensen zichzelf voeden en voorzien in hun meest belangrijke levensbehoeften terwijl ze thuis moeten blijven?',
    'How does it work?' => 'Hoe werkt het?',
    '“I would like to get help”' => '“Ik heb hulp nodig”',
    'Print out your shopping list and ask your neighbour to do the shopping for you.' => 'Print de boodschappenlijst uit of vraag aan uw buurman om het voor jou te doen.',
    'Stick it to your door or put it in the hallway.' => 'Plaats het op je raam, plak het op je deur of plaats het in je lobby/inkomsthal.',
    'Wait for a helping neighbour to fetch the list. (S)He will contact you and deliver to you as soon as possible.' => 'Wacht tot een helpende buur de lijst komt ophalen. Hij/Zij neemt contact met u op en levert het u zo snel mogelijk.',
    'Print out your shopping list' => 'Print de boodschappenlijst',
    'Find someone to help me' => 'Iemand vinden om mij te helpen',
    '“I can help”' => '“Ik ben een vrijwilliger en ik wil helpen...”',
    '<a class="text-underline" href="https://docs.google.com/forms/d/e/1FAIpQLSftvX-pPQZePG8K46Npk8pBvUUP5Da7MP8CXPbtL-wAz0spcw/viewform" target="_blank"><u><b>Fill out this form</b></u></a> 📝' => '<a class="text-underline" href="https://docs.google.com/forms/d/e/1FAIpQLSftvX-pPQZePG8K46Npk8pBvUUP5Da7MP8CXPbtL-wAz0spcw/viewform" target="_blank"><u><b>Vul deze vorm in</b></u></a> 📝',
    '<a class="text-underline" href="./files/EN.pdf" target="_blank"><u><b>Print out the template</b></u></a> “shopping list” in A4 format 🖨️' => '<a class="text-underline" href="./files/NL.pdf" target="_blank"><u><b>Druk het </b></u></a> "boodschappenlijstje" sjabloon af in A4-formaat 🖨️',
    'Share it or place it in your neighbour’s mailbox 📬' => 'Deel deze lijst of stop het in de brievenbus van je buurman. 📬',
    'Go back home and enjoy a coffee ☕' => 'Ga naar huis en praat met je gezin rond een tas koffie. ☕',
    'Take your neighbour’s filled in shopping list and tell him/her you’ll go shop for him 🚶' => 'Neem van een foto van de ingevulde boodschappenlijst van je buur. Bel/sms hem km te zeggen dat je om boodschappen bent. 📝',
    'Go to the store, try not to empty the shelves if you have what you need, be mindful to others. 📝' => 'Ga naar de winkel en overval de schappen niet. 🎒',
    'Preferably use a shopping cart instead of a shopping basket, you create additional distance. 🛒' => 'Gebruik bij voorkeur een winkelkar in plaats van een winkelmandje, zo creëer je meer ruimte. 🛒',
    'Come alone. 🚶‍♂️' => 'Kom alleen. 🚶‍♂️️',
    'Only touch products you are gonna buy. 🤚' => 'Raak enkel producten aan die je koopt. 🤚',
    'Pay electronically. 💳' => 'Betaal elektronisch. 💳',
    'Go back to your neighbour’s home, put the groceries down in front of the door, and ring! 🎒' => 'Lever de producten, zet ze voor de deur van de buurman/-vrouw en bel aan! 🚪',
    '<b>Mission accomplished, thank you very much for your help!</b> 🚀 💚' => '<b>Missie geslaagd, heel erg bedankt voor de samenwerking!</b> 🚀 💚',
    'Now you can also share a picture on Facebook or Instagram with #covidsolidarity 📸' => 'Deel een foto op Facebook met de hashtag #HelpYourNeighbour 📸',
    'Rules to respect' => 'Te respecteren maatregelen',
    'Wear gloves when you go shopping (when you take the groceries and put them in the bags). Touch only the products you buy.' => 'Doe handschoenen aan als u gaat shoppen (als u de producten neemt en ze in de shopping bag legt). Raak alleen maar producten aan die u zal kopen.',
    'Use a shopping cart instead of a shopping bag, you create thus additional distance.' => 'Gebruik een karretje in de plaats van een mand, dan kunt u meer afstand maken.',
    'Preferably come alone.' => 'Kom beter alleen.',
    'Keep a distance of 3 meters between the receiver and the volunteer. By all means, avoid physical contact, practice social distancing with vulnerable people. Avoid social contact as much as possible.' => 'Houd een afstand van 3 meter tussen de geïsoleerde persoon en de vrijwilliger en vermijd lichamelijk contact en contact met kwetsbare mensen. Vermijd ook contact met andere mensen.',
    'Wash your hands regularly or use a hand disinfectant after the delivery (this is for both the receiver and the volunteer of the delivery)' => 'Was uw handen regelmatig of gebruik een hydro-alcoholische oplossing, vooral na de bevalling (zowel de persoon als de vrijwilliger).',
    'Avoid touching door handles and other metallic objects during the delivery. When contacting between the receiver and the volunteer, communicate by phone or through a message application (WhatsApp or Messenger for example).' => 'Vermijd het aanraken van deurklinken en andere metalen voorwerpen tijdens de levering. Geef de voorkeur aan oproepen of berichten/whatsapp.',
    'Pay electronically.' => 'Betaal elektronisch.',
    'Cover your mouth and nose with a tissue when you cough or sneeze or use the inside of your elbow.' => 'Als je geen zakdoek bij de hand hebt, nies of hoest dan in de plooi van je elleboog.',
    'Be careful with vulnerable groups i.e. Senior-aged individuals +65, diabetics, people suffering from heart diseases, pulmonary insufficiency, renal failure, and immunosuppressed patients and many others.' => 'Besteed aandacht aan risicogroepen (mensen ouder dan 65 jaar, diabetici, mensen met een hart-, long- of nierziekte, mensen met immuunproblemen...).',
    'If a volunteer is not delivering we recommend you stay home safe and avoid social contact.' => 'De rest van de tijd (wanneer u geen leveringen doet) nodigen wij u uit om thuis te blijven en uw contact met andere mensen zoveel mogelijk te beperken.',
    'For more information visit our page: <a href="https://www.info-coronavirus.be/" target="_blank">https://www.info-coronavirus.be/</a>' => 'Meer details over : <a href="https://www.info-coronavirus.be/nl/" target="_blank">https://www.info-coronavirus.be/nl/</a>',
    'Do you have any questions ? We’ve got the answers !' => 'Heeft u vragen? We hebben de antwoorden!',
    '“I would like to help”' => '“Ik ben een vrijwilliger en ik wil helpen”',
    'Will I get paid to help my neighbour?' => 'Word ik betaald om mijn buurman/-vrouw te helpen?',
    'No, we are acting strictly on a voluntary basis. But of course your neighbour is free to decide how (s)he would like to thank you.' => 'Nee, we handelen in een strikte burger- en vrijwilligers aanpak. Maar je buurman/-vrouw is vrij om je te bedanken als hij/zij dat wil.',
    'I don’t want to pay the money upfront' => 'Ik wil geen geld voorschieten',
    'This is a condition you need to fill in order to help your neighbour. Not to make it too expensive, we advise you to only provide for basic needs.' => 'Dit is een noodzakelijk voorwaarde voor het helpen van een buurman/-vrouw. Om de uitgaven te beperken, vragen we om enkel basisbenodigdheden te kopen.',
    'How to hand over groceries to someone inside a building?' => 'Hoe lever ik boodschappen af in een appartementsgebouw?',
    'You just have to make contact with the person you want to do the shopping for, and tell him at what time you will put the groceries in front of his door. Don’t forget rules for proper hygiene.' => 'Het volstaat contact op te nemen met uw buurman/-vrouw om hem/haar te laten weten op welk tijdstip u de boodschappen voor zijn/haar deur achterlaat. Vergeet niet de regels van hygiëne te respecteren.',
    'How will I get refunded?' => 'Hoe word ik vergoed?',
    'It’s very simple ! The only thing you have to do is to write down your bank account number on the shopping list that you will give back to your neighbour. Your neighbour will pay you back as soon as possible.' => 'Het is heel eenvoudig! U hoeft alleen maar uw rekeningnummer aan te geven op het boodschappenlijstje dat u aan uw buurman/-vrouw geeft. Voor de goede dienstverlening zal hij/zij u onmiddellijk terugbetalen.',
    'Can I contact the person who helped me again in the future?' => 'Kan ik later weer contact opnemen met de vrijwillige helper/ster?',
    'Of course ! The goal is that the two of you can meet in order to create a relationship of trust. Nevertheless, do not forget the rules of hygiene in order to stay safe.' => 'Natuurlijk! De bedoeling is dat je mensen ontmoet waar je een vertrouwensrelatie mee opbouwt. U kunt de vrijwillige helper/ster dus terugbellen wanneer u maar wilt. Vergeet echter niet strenge hygiënevoorschriften na te leven om altijd veilig te blijven.',
    'How to know who is shopping for me?' => 'Hoe weet ik wie mijn boodschappen doet?',
    'When your helper takes your shopping list, he will contact you on your phone number to inform you that (s)he is on her/his way.' => 'Wanneer u uw boodschappenlijstje ophaalt, neemt de vrijwillige helper/ster contact met u op via uw vaste of mobiele telefoonnummer om u te laten weten dat hij of zij op weg is naar de winkel. Hij/Zij laat het je ook weten als hij/zij op de terugweg is.',
    'I am not able to easily send money' => 'Ik ben niet in de mogelijkheid om een eenvoudige betaling te doen.',
    'You can ask a friend or a family member to help you pay back the person who did the shopping for you or download a payment application on your mobile phone. The best is to ask for help.' => 'U kunt een familielid vragen om u te helpen de vrijwilliger te vergoeden of om betaalapplicaties te downloaden op uw mobiele telefoon.',
    'What is the maximum amount that I can order for?' => 'Wat is het maximale bedrag waarvoor ik kan bestellen?',
    'You can order for as much as you’d like, but we advise not to go over 25 to 30 euros and focus on your basic needs. Also mind the weight of the shopping bag, the person who will deliver it to you will have to carry it.' => 'Zoals u wenst, maar we stellen voor om een bedrag van 25 tot 30€ niet te overschrijden en u te concentreren op de basisbehoeften. Denk ook aan het uiteindelijke gewicht van je pakket, de vrijwillige helper moet ermee kunnen rondlopen.',
    'With the help of' => 'Met de steun van',
    'A 100% voluntary initiative' => 'Een 100% vrijwillig en burgerinitiatief',
    'We were touched by the way the Covid-19 crisis turned out to affect our community. This epidemic forced us to find pragmatic solutions to bring help to those in need. We decided to serve the population through collective intelligence.' => 'Wij zijn geraakt door de snel veranderende actualiteit en ons ervan bewust dat deze crisis ons dwingt om pragmatische oplossingen te vinden voor hulpvragen, zo hopen we beroep te doen op het collectief gezond verstand om zo hulp te verlenen aan de bevolking.',
    'A non-profit citizen movement created online by a group of entrepreneurs and students from the BeTech Community who wanted to create a positive social impact .' => 'Een burgerbeweging zonder winstoogmerk die online is opgericht werd door een groep ondernemers en studenten uit de BeTech Community die een positieve sociale impact wil creëren.',
    '❤️ Made with love to beat Covid-19' => '❤️ Made with love to beat Covid-19',
    'Contact' => 'Contact',
    'Join the movement on Facebook' => 'Join the movement on Facebook',
);
